# Welcome to Jekyll!
# This config file affects your whole blog/site.

# Site settings
title: Sripadam Sujith Sai
email: ssujith.sai04@gmail.com
description: >-
  A personal blog showcasing posts, projects, and ideas.
baseurl: "" # e.g. "/blog" if deployed to GitHub Pages under a subdirectory
url: "https://sujithsaisripadam.github.io" # Set to your domain or GitHub Pages URL

social:
  linkedin_username: sripadam-sujith-sai
  github_username: SujithSaiSripadam

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true

# Exclude from processing
exclude:
  - README.md
  - node_modules/
  - vendor/

permalink: /:categories/:year/:month/:day/:title.html

# Custom variables (you can use these in your templates like {{ site.author_name }})
author_name: Sujith Sai
